### ISSUE TITLE
Cannot create file 

### ISSUE THREAD

**Issue by baygaillardclasspass** [mario-campos/gh-code-scanning#12]
I am getting the following over and over when I try to run the tool to enable a bunch of repositories:
```
2022-10-10 10:15:22,918 49479 ERROR classpass/ml-training: cannot create file ".github/workflows/codeql-analysis.yml": gh: Not Found (HTTP 404)
```

**Comment by mario-campos** [comment]
Make sure `gh` is authenticated (`gh auth status`) and that your account has permission to the repo.

**Comment by baygaillardclasspass** [comment]
```
bay.gaillard@N2NMP2N567 aws-arcus-kitchensink % gh auth status
github.com
  ✓ Logged in to github.com as baygaillardclasspass (oauth_token)
  ✓ Git operations for github.com configured to use ssh protocol.
  ✓ Token: *******************
```

I have write access to the repository, and was able to create a branch successfully - the 404 comes on the create file call.

**Comment by baygaillardclasspass** [comment]
This is the first github action on the repository, could it be complaining that the folder of actions isn't there?

**Comment by baygaillardclasspass** [comment]
Nevermind, it fails with the same error on a repo I've alreayd manually enabled codeql scanning on, so the folder is there

**Comment by mario-campos** [comment]
I would try to reproduce it in `gh` the same way that [`create_file`](https://github.com/mario-campos/gh-code-scanning/blob/master/gh-code-scanning#L69) calls `gh`. You can get more debug output with `-vv` and even see the `gh` command.

Once you've got the `gh` command, play around with it and experiment with the different params to find out why it's not working.

**Comment by baygaillardclasspass** [comment]
Here's a gist of the debug output so you can also take a poke at it while I investigate: https://gist.github.com/baygaillardclasspass/64f156b3efa4b910c32ad89907c2d172

**Comment by baygaillardclasspass** [comment]
I found a lead: https://github.com/orgs/community/discussions/24682

**Comment by mario-campos** [comment]
Good call! Thanks. I'll add it to the wiki and link it from the README.
