### ISSUE TITLE
Add an option to push a custom workflow file instead then the autogenerated one

### ISSUE THREAD

**Issue by mbaluda** [mario-campos/gh-code-scanning#2]
It would be useful to be able to skip the workflow file generation and allow instead the user to push a custom workflow yml file.

**Comment by mario-campos** [comment]
I had a feeling someone might want this feature. I'm not opposed to it. If I have some time, I'll get to it. For now, as a workaround, you can navigate to the extension's directory (somewhere in `~`) and modify the YML file.

**Comment by mario-campos** [comment]
This was implemented by @zerotyr with PR #9.
